services:
  db:
    # PostgreSQL database
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  # Database interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080